// import '~/styles/antd.min.css'
// import 'antd/dist/reset.css';
import "./globals.scss";
import "~/styles/_base.scss";
import { Inter } from "next/font/google";
import { RootStyleRegistry } from "~/config/rootStyleRegistry";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootStyleRegistry>{children}</RootStyleRegistry>
      </body>
    </html>
  );
}
